// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// SOMF_cpp
SEXP SOMF_cpp(SEXP Xin, SEXP Win, SEXP Hin, SEXP betain, SEXP rhoin, SEXP num_iterin);
RcppExport SEXP _MOMF_SOMF_cpp(SEXP XinSEXP, SEXP WinSEXP, SEXP HinSEXP, SEXP betainSEXP, SEXP rhoinSEXP, SEXP num_iterinSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type Xin(XinSEXP);
    Rcpp::traits::input_parameter< SEXP >::type Win(WinSEXP);
    Rcpp::traits::input_parameter< SEXP >::type Hin(HinSEXP);
    Rcpp::traits::input_parameter< SEXP >::type betain(betainSEXP);
    Rcpp::traits::input_parameter< SEXP >::type rhoin(rhoinSEXP);
    Rcpp::traits::input_parameter< SEXP >::type num_iterin(num_iterinSEXP);
    rcpp_result_gen = Rcpp::wrap(SOMF_cpp(Xin, Win, Hin, betain, rhoin, num_iterin));
    return rcpp_result_gen;
END_RCPP
}
// MOMF_cpp
SEXP MOMF_cpp(SEXP Xin, SEXP Win, SEXP Uin, SEXP betain, SEXP rhoin, SEXP num_datain, SEXP num_iterin);
RcppExport SEXP _MOMF_MOMF_cpp(SEXP XinSEXP, SEXP WinSEXP, SEXP UinSEXP, SEXP betainSEXP, SEXP rhoinSEXP, SEXP num_datainSEXP, SEXP num_iterinSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type Xin(XinSEXP);
    Rcpp::traits::input_parameter< SEXP >::type Win(WinSEXP);
    Rcpp::traits::input_parameter< SEXP >::type Uin(UinSEXP);
    Rcpp::traits::input_parameter< SEXP >::type betain(betainSEXP);
    Rcpp::traits::input_parameter< SEXP >::type rhoin(rhoinSEXP);
    Rcpp::traits::input_parameter< SEXP >::type num_datain(num_datainSEXP);
    Rcpp::traits::input_parameter< SEXP >::type num_iterin(num_iterinSEXP);
    rcpp_result_gen = Rcpp::wrap(MOMF_cpp(Xin, Win, Uin, betain, rhoin, num_datain, num_iterin));
    return rcpp_result_gen;
END_RCPP
}
// MOMF_fixU_cpp
SEXP MOMF_fixU_cpp(SEXP Xin, SEXP Win, SEXP Uin, SEXP Uplusin, SEXP betain, SEXP rhoin, SEXP num_datain, SEXP num_iterin);
RcppExport SEXP _MOMF_MOMF_fixU_cpp(SEXP XinSEXP, SEXP WinSEXP, SEXP UinSEXP, SEXP UplusinSEXP, SEXP betainSEXP, SEXP rhoinSEXP, SEXP num_datainSEXP, SEXP num_iterinSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type Xin(XinSEXP);
    Rcpp::traits::input_parameter< SEXP >::type Win(WinSEXP);
    Rcpp::traits::input_parameter< SEXP >::type Uin(UinSEXP);
    Rcpp::traits::input_parameter< SEXP >::type Uplusin(UplusinSEXP);
    Rcpp::traits::input_parameter< SEXP >::type betain(betainSEXP);
    Rcpp::traits::input_parameter< SEXP >::type rhoin(rhoinSEXP);
    Rcpp::traits::input_parameter< SEXP >::type num_datain(num_datainSEXP);
    Rcpp::traits::input_parameter< SEXP >::type num_iterin(num_iterinSEXP);
    rcpp_result_gen = Rcpp::wrap(MOMF_fixU_cpp(Xin, Win, Uin, Uplusin, betain, rhoin, num_datain, num_iterin));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_hello_world
List rcpp_hello_world();
RcppExport SEXP _MOMF_rcpp_hello_world() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(rcpp_hello_world());
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_MOMF_SOMF_cpp", (DL_FUNC) &_MOMF_SOMF_cpp, 6},
    {"_MOMF_MOMF_cpp", (DL_FUNC) &_MOMF_MOMF_cpp, 7},
    {"_MOMF_MOMF_fixU_cpp", (DL_FUNC) &_MOMF_MOMF_fixU_cpp, 8},
    {"_MOMF_rcpp_hello_world", (DL_FUNC) &_MOMF_rcpp_hello_world, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_MOMF(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
