# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

SOMF_cpp <- function(Xin, Win, Hin, betain, rhoin, num_iterin) {
    .Call('_MOMF_SOMF_cpp', PACKAGE = 'MOMF', Xin, Win, Hin, betain, rhoin, num_iterin)
}

MOMF_cpp <- function(Xin, Win, Uin, betain, rhoin, num_datain, num_iterin) {
    .Call('_MOMF_MOMF_cpp', PACKAGE = 'MOMF', Xin, Win, Uin, betain, rhoin, num_datain, num_iterin)
}

MOMF_fixU_cpp <- function(Xin, Win, Uin, Uplusin, betain, rhoin, num_datain, num_iterin) {
    .Call('_MOMF_MOMF_fixU_cpp', PACKAGE = 'MOMF', Xin, Win, Uin, Uplusin, betain, rhoin, num_datain, num_iterin)
}

rcpp_hello_world <- function() {
    .Call('_MOMF_rcpp_hello_world', PACKAGE = 'MOMF')
}

